name: Deploy EKS Cluster

on:
  workflow_dispatch:  # Trigger workflow on push to main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Repository
    - name: Checkout Code
      uses: actions/checkout@
      
    - name: Print Working Directory
      run: pwd

    # Step 2: Set Up Terraform
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.4.6"

    # Step 3: Terraform Init
    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform
      
    - name: Print Working Directory
      run: pwd

    - name: Display Terraform Files
      run: ls -l ./terraform

    # Step 4: Terraform Plan
    - name: Terraform Plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      run: terraform plan
      working-directory: ./terraform

    # Step 5: Terraform Apply
    - name: Terraform Apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      run: terraform apply -auto-approve
      working-directory: ./terraform