name : 'Terraform'

on:
  push:
    branches: ["devo1"]
jobs:
  terraform:
    name: 'Terraform'
    env:
      #AWS Secrets
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    environment: production

    steps:
    #checkout code
    - name: checkout
      uses: actions/checkout@v3


    - name: Terraform Init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_action_version: 1.9.2
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: '.'
        tf_actions_comment: true



    - name: Terraform plan
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_action_version: 1.9.2
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: '.'
        tf_actions_comment: true
  

    - name: Terraform apply
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_action_version: 1.9.2
        tf_actions_subcommand: 'apply'
        tf_actions_working_dir: '.'
        tf_actions_comment: true
       
